fn main() {
    // Generate C header file during build
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let output_file = std::path::Path::new(&crate_dir).join("xmtp_ffi.h");
    
    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        include_guard: Some("XMTP_FFI_H".to_string()),
        no_includes: true,
        autogen_warning: Some("/* DO NOT MODIFY: This file is auto-generated by cbindgen */".to_string()),
        documentation: true,
        ..Default::default()
    };
    
    if let Ok(bindings) = cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .generate()
    {
        bindings.write_to_file(output_file);
    }
}
